### ISSUE TITLE
Skins don't load correctly [Solved]

### ISSUE THREAD

**Issue by AntoninoWGF** [Namensammler42/CosmicNPCs#2]
Hello, I've found a bug in the mod which doesn't load the skins correctly and shows a missing texture skin. In the folder there are only new format skins (64x64) but only one of them works, the others won't work. **Help me please!** _Edit: I solved the problem by making the file names all lowercase._

**Comment by infi** [comment]
It would be helpful if you included details such as

1. Mod version
2. Minecraft version
3. Detailed steps on how to reproduce the issue

**Comment by Namensammler42** [comment]
Minecraft doesn't allow texture files to have names with upper-case letters. So yeah as you already found out, skin files need to be all lowercase.
